### ISSUE TITLE
Change CI service

### ISSUE THREAD

**Issue by fxn** [rails/rails-contributors#123]
CircleCI runs the test suite when we merge to `master`, but apparently as of this writing CircleCI [does not support checking PRs](https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213/29).

Guess we have to switch to Travis? What do you think @yhirano55?

**Comment by rafaelfranca** [comment]
That is strange. We used circle CI at Shopify and I'm sure it runs builds on PRs. I not any configuration missing?

**Comment by rafaelfranca** [comment]
Ah, rack also uses circle CI and all PRs have builds for circle CI. https://github.com/rack/rack/pull/1314

**Comment by fxn** [comment]
Sure I have missed some documentation.

**Comment by rafaelfranca** [comment]
I fixed this issue on Circle CI some months ago and forgot to close it. We don't need to change CIs anymore.
