### ISSUE TITLE
Can we redeploy with updated aliases?

### ISSUE THREAD

**Issue by rmacklin** [rails/rails-contributors#129]
Hi,

I noticed that the alias I added in https://github.com/rails/rails-contributors/pull/127 does not seem to be reflected on the live site. Is this because we haven't deployed the application after that was merged? If so, can we redeploy? If not, did I make a mistake in https://github.com/rails/rails-contributors/pull/127?

Thanks!

**Comment by rafaelfranca** [comment]
The deploy was made and it seems the alias is working. Thank you
