### ISSUE TITLE
Understand Co-Authored-By

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails-contributors#133]
GitHub now add a `Co-Authored-By` to the commit message when you squash the PR on merge. It would be good if we start to understand that to give the authorship to both the committer and the person on `Co-Authored-By`.

**Comment by rafaelfranca** [comment]
cc @fxn

**Comment by fxn** [comment]
Agree.

My next thing is to revamp the constants guide before final, could take this after it.

**Comment by itsWill** [comment]
Just encountered this on a joint commit with @gmcgibbon: https://github.com/rails/rails/pull/36521

@fxn I have some bandwidth so I can take a stab at this issue, if you're still busy with the constants guide.

**Comment by fxn** [comment]
@itsWill help very welcome, go ahead :).
