### ISSUE TITLE
Split contributions issue

### ISSUE THREAD

**Issue by davidauza-engineer** [rails/rails-contributors#154]
Hi

Today I was checking my contributions on [the app](https://contributors.rubyonrails.org) and I found that my contributions are split like shown below in the captures:

<img width="1281" alt="Screen Shot 2020-03-16 at 3 59 45 PM (2)" src="https://user-images.githubusercontent.com/47565678/76799274-31baad00-679f-11ea-88c4-0da5ffaeccd8.png">

<img width="1281" alt="Screen Shot 2020-03-16 at 4 00 29 PM (2)" src="https://user-images.githubusercontent.com/47565678/76799355-557df300-679f-11ea-999b-3095af2462cc.png">

Trying to find a solution I followed the recommendation on the FAQ section and modified [this file](https://github.com/rails/rails-contributors/blob/master/app/models/names_manager/canonical_names.rb) and then open the following pull request:

#155 

Could you guys please confirm if that is right in order for my contributions to appear only as 'David Auza'?

Thank you very much,

Best regards from Colombia 🇨🇴 ,

[David Auza](https://github.com/davidauza-engineer)

**Comment by rafaelfranca** [comment]
Done https://contributors.rubyonrails.org/contributors/david-auza/commits

**Comment by davidauza-engineer** [comment]
Thank you very much @rafaelfranca 👍
