### ISSUE TITLE
Contradictory FAQ Text

### ISSUE THREAD

**Issue by kristophertope** [rails/rails-contributors#270]
The FAQ page contains these two contradictory sentences:

Multiple authors
**Git has no support for multiple authors**, and again the project has figured out conventions to give credit for one commit to several people.

Multiple authors through Co-authored-by
**GitHub has added support for multiple authors** by using Co-authored-by annotations, see [here](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) for more information.

I suggest combining "Multiple authors" and "Multiple authors through Co-authored-by" into one section that explains how the app handles co-author scenarios both before and after GitHub support was added.

**Comment by fxn** [comment]
Let us consider the proposal, but let me remark the statements are not contradictory. Git is not GitHub.

**Comment by fxn** [comment]
Thanks for your suggestion, the sections were indeed merged:

![CleanShot 2024-01-01 at 18 31 48@2x](https://github.com/rails/rails-contributors/assets/3387/9e2c9b14-77d1-49a0-b329-3f55a284962c)

**Comment by kristophertope** [comment]
Excellent!
